name: Doxygen GitHub Pages Deploy Action

on:
  push:
    branches:
      - main
  pull_request: # Just to test if works for now
    branches: [ "main" ]


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: DenverCoder1/doxygen-github-pages-action@v1.3.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
